### ISSUE TITLE
Few issues & queries!

### ISSUE THREAD

**Issue by karandatwani92** [redsquirrelstudio/laravel-backpack-import-operation#6]
Hey @redsquirrelstudio 

I just completed my exploration of your import package. I must say, It's a very very cool package.😎

I'm going to use it in two of my projects. ❤️🙏

During my testing, I found a few things not working. Let me know if I missing something.

- [x] [Column is not being set during import](https://github.com/redsquirrelstudio/laravel-backpack-import-operation/issues/4)
- [x] `$this->queueImport()` throws [error](https://flareapp.io/share/q5YqdOo5). IDK why it still passes `CrudImport`. I understand it expects`QueuedCrudImport`.
- [x] #7
- [x] Files don't get deleted after completion. Is it ok?
- [ ] Validation didn't work for me!
- [x] Correct `ExampleColumn` path in Readme `'type' => \App\Imports\Columns\ExampleColumn::class,`
- [x] I can't import the same column for two or more columns.🚨
 -- If I'm choosing the same column as input for two columns(I intentionally chose primary key), I get the following error because the keys get overlapped:
![Screenshot 2024-01-16 at 7 44 41 PM](https://github.com/redsquirrelstudio/laravel-backpack-import-operation/assets/8214221/0b5ad054-bb6e-4f00-ab55-aa8528122b14)

**I tried every option you are offering & found them sorted.**
- Installation✅
- Primary Keys✅
- Adding an Example File✅
- All Column Types✅
- Adding Your Own Columns✅
- Custom Import Classes✅
- Disabling User Mapping✅

Let's go through with these too. I will publish an article about this package soon.

Cheers!

**Comment by redsquirrelstudio** [comment]
Hi @karandatwani92 

Thanks for your kind words and sending through these issues!

I'll allocate some time to get these sorted to make the package perfect :)

Many thanks!

**Comment by redsquirrelstudio** [comment]
Hi again @karandatwani92 

I'm currently working through those issues,

Can I check for "Validation didn't work for me!"
Could you send through the validator class and spreadsheet layout please :)

Many thanks!

**Comment by redsquirrelstudio** [comment]
As a quick update, I have added the following changes @karandatwani92 

- Queued imports have been fixed
- The array column now supports ```'options' => 'any'``` when 'multiple' is set to true, this allows any comma separated values to be imported.
- ```$this->deleteFileAfterImport();``` can be added to the setup function to delete the file after import.
- The README has been updated to make adding the custom column alias more clear.
- You can now import the same spreadsheet column into multiple model fields.

Thank you very much for these suggestions as I believe they have made the package much more complete :) 
I'll await on further information about your validation issue before merging and publishing this branch.

**Comment by redsquirrelstudio** [comment]
@karandatwani92 What was the behaviour you were expecting from validation?

**Comment by karandatwani92** [comment]
Nice work! @redsquirrelstudio
I tested `feature-fix_issues` branch. I find most of them fixed.✅

- Now, I'm facing [issue](https://flareapp.io/share/lm22Mj0m) with `$this->disableUserMapping()`.🚨 Earlier, it was working!
- `queueImport()` worked & I think there is scope for enhancement.
- Validations `CRUD::setValidation(MemberRequest::class);` still not working!

As per Readme, I'm assuming the following:
![Screenshot 2024-01-19 at 1 24 24 PM](https://github.com/redsquirrelstudio/laravel-backpack-import-operation/assets/8214221/3314d910-04bc-48ea-a888-1264b4f61f76)

**Let's proceed for now by merging this branch.🎉
We take care of the above issues separately.**


Thanks for everything - your efforts, fast response, interest and this cool package.😎

Have a great day!

**Comment by redsquirrelstudio** [comment]
Thank you for the feedback, I think I know the issue with disable user mapping, and I'll update this within this pull request.

I agree, that the validation can be made into a separate issue.

At the moment validation simply validated each row in the import and skips them if they don't pass. I'll continue my thoughts in the other issue. 

Many thanks for the tests, I'll update shortly with the disable user mapping fix. 😁

**Comment by redsquirrelstudio** [comment]
Hi again @karandatwani92 

The disable user mapping issue is now fixed in the latest commit, was a bug introduced by the new multi-column import support :D

Many thanks again for your help testing this.

**Comment by redsquirrelstudio** [comment]
Release v1.6.2 has been published containing these fixes/updates.
